### ISSUE TITLE
Sony xperia 5 Sony Open Devices

### ISSUE THREAD

**Issue by aret1nol** [sonyxperiadev/device-sony-bahamut#2]
Hello! I'm from Russia. I would like to buy a sony xperia 5 phone. I want to modify the standard firmware and for this I need to unlock the bootloader.
Unlocking the bootloader, as I understand it, is not possible on all models. How do I determine before a purchase in a store that a specific phone can unlock the bootloader?
Is it possible to unlock the bootloader on all sony xperia 5 phones that are sold in Russia?
Can I expect that the new sony xperia models that will be released in 2020 will also be added to the Sony Open Devices program?
The links that I used:
https://developer.sony.com/posts/xperia-5-added-to-sonys-open-devices-program/
https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/

**Comment by bartcubbins** [comment]
On all devices that were not purchased under a contract and do not have a binding to a specific operator, you can unlock the bootloader. You can check the bootloader status using the service menu that is called through the dialer: `*#*#7378423#*#*` -> Service Info -> Configuration -> Rooting status. If it says "Bootloader unlock allowed: Yes" then you can easily unlock your bootloader.
All QCOM SoC based devices are added to the open devices program.
