### ISSUE TITLE
Sony xperia 5 AOSP (Flash vendor image to your device)

### ISSUE THREAD

**Issue by Natalia-Oreiro** [sonyxperiadev/device-sony-bahamut#3]
old

**Comment by MarijnS95** [comment]
You can find an overview of all vendor binaries here:
https://developer.sony.com/develop/open-devices/downloads/software-binaries

Bahamut is also available: it shares the same blobs as Griffin, which are the same platform (Kumano).

Looks like that page was simply not updated to include the link.

**Comment by Natalia-Oreiro** [comment]
Thank you for the information, is this tutorial really working for AOSP Xperia 5 with Android 10?

I'm getting worried: https://i.imgur.com/Fd5bquI.png

**Comment by MarijnS95** [comment]
The guide is a copy-paste from Android 9 and has apparently not been fully adjusted. It is after all identical, apart from the branch numbers.

Support for Bahamut is totally decoupled from that tutorial. As of writing you can compile AOSP for the device and boot it, but certain core functionality is missing. I suggest to wait for vendor binaries v4 which are scheduled for release soon and address some critical issues.

**Comment by Natalia-Oreiro** [comment]
> I suggest to wait for vendor binaries v4 which are scheduled for release soon and address some critical issues.

Thank you for notifying me, where did you get this information?
do you have this information as an internal developer or follow any forum or section here on github?

**Comment by jerpelea** [comment]
please use the bug tracker
